### ISSUE TITLE
Support for NX-OS 

### ISSUE THREAD

**Issue by net9000** [routetehpacketz/cisco-ip-trace#9]
Switch ports coming back as 'Unknown' and not sure why.  This end host is on the far end of switch via a port-channel off the core.   

```
`(p3-env) admin@admin:/tmp$ python cisco_ip_trace.py
Enter target in CIDR notation (192.168.10.0/24): 192.168.17.20
Enter VRF for the IP. Press 'Enter' if you're not using VRFs:
Enter the IP address of the core router/switch that can ARP for the IP address to trace: 192.168.1.1
Username: admin
Password:
Enter a filename to save output as CSV (leave blank for no file output):

Tracing 192.168.17.20...Port Unknown
Device IP,MAC Address,Switch,Port,Port Description,Interface Type,VLANs on port,Port MAC count
192.168.17.20,**686d.bc06.4cac**,r187-9600,Unknown`
```

However I can see it from the mac address-table from the switch its connected to:

`sw87-2960#sho mac address-table | i 4cac
  17    **686d.bc06.4cac**    STATIC      Gi2/0/13`

**Comment by net9000** [comment]
I dl'd your debug script from the closed issue and this is what it returns:

`Do you want to scan a single IP or a range?

1. Single IP

2. Range (must be contiguous; no greater than /24)

Please input 1 or 2: 1
Enter IP address to trace: 192.168.17.20
Enter the IP address of the core router/switch that can ARP for the IP address to trace: 192.168.1.1
Username: admin
Password:
Line 67

term len 0
9300#ping 192.168.17.20 rep 2
Type escape sequence to abort.
Sending 2, 100-byte ICMP Echos to 192.168.17.20, timeout is 2 seconds:
!!
Success rate is 100 percent (2/2), round-trip min/avg/max = 1/1/1 ms
9300#show ip arp 192.168.17.20 | inc 192.168.17.20
Internet  192.168.17.20            4   686d.bc06.4cac  ARPA   Vlan17
9300#


Line 69

686d.bc06.4cac


Line 117

show mac add add 686d.bc06.4cac | inc 686d.bc06.4cac
  17    686d.bc06.4cac    DYNAMIC     Po3
9300#


Traceback (most recent call last):
  File "debug.py.py", line 261, in <module>
    main()
  File "debug.py.py", line 257, in main
    singleip_scan()
  File "debug.py.py", line 240, in singleip_scan
    cdp_nei_ip,match_mac=core(core_router,current_ip)
  File "debug.py.py", line 120, in core
    print('Line 120\n\n'+mac_port.group()+'\n\n')
AttributeError: 'NoneType' object has no attribute 'group'
(p3-env) admin@dadmin:/tmp$
`

**Comment by routetehpacketz** [comment]
Hey @net9000,

The debug script is erroring out because it is trying to print a variable that has not populated yet. The actual trace script has handling for this.

What is the output of `show ether-channel summary | inc Po3` on your core switch?

**Comment by net9000** [comment]
```
#show etherchannel sum | i Po3
3      Po3(SU)         LACP      Te1/1/1(P)  Te1/1/2(P)
```

**Comment by routetehpacketz** [comment]
Ah it's a Nexus. Adding functionality for Nexus switches is on the list of to-dos. A Reddit user has been in contact with me recently inquiring when it can be added. I had started working on it this week, but there is more to it than I initially thought. I will change this Issue to reflect a feature request for supporting NX-OS and will try to complete it as soon as I can.

**Comment by net9000** [comment]
@routetehpacketz 

Question about this.   I am seeing an issue with the script when it tires to ssh into a Nexus device from the core. Instead of SSH'ing into the management IP its trying to SSH into the VPC peer link IP.  The script tires to ssh into 10.2.12.2, but can't because the VPC peer IP isn't routed outside of the 5ks.  So why doesn't the script use the 10.1.1.5 (Mgmt IP) vs 10.2.12.2 (VPC peer IP)?

```
Device ID: nexus5k-switch(SSI15510NK4)
Entry address(es):
  IP address: 10.1.1.5
Platform: N5K-C5548UP,  Capabilities: Switch IGMP CVTA phone port
Interface: GigabitEthernet1/2/46,  Port ID (outgoing port): mgmt0
Holdtime : 150 sec

Version :
Cisco Nexus Operating System (NX-OS) Software, Version 5.2(1)N1(3)

advertisement version: 2
Duplex: full
Management address(es):
  IP address: 10.1.1.5

-------------------------
**Device ID: nexus5k-switch(SSI15510NK4)
Entry address(es):
  IP address: 10.2.12.2
Platform: N5K-C5548UP,  Capabilities: Switch IGMP CVTA phone port
Interface: TenGigabitEthernet1/5/5,  Port ID (outgoing port): Ethernet1/7
Holdtime : 150 sec**

Version :
Cisco Nexus Operating System (NX-OS) Software, Version 5.2(1)N1(3)

advertisement version: 2
Native VLAN: 1
Duplex: full
Management address(es):
  IP address: 10.1.1.5

-------------------------
**Device ID: nexus5k-switch(SSI15510NK4)
Entry address(es):
  IP address: 10.2.12.2
Platform: N5K-C5548UP,  Capabilities: Switch IGMP CVTA phone port
Interface: TenGigabitEthernet2/5/5,  Port ID (outgoing port): Ethernet1/8
Holdtime : 144 sec**

Version :
Cisco Nexus Operating System (NX-OS) Software, Version 5.2(1)N1(3)

advertisement version: 2
Native VLAN: 1
Duplex: full
Management address(es):
  IP address: 10.1.1.5

```

**Comment by routetehpacketz** [comment]
hey @net9000 

I can't say exactly why it's using the VPC address since it's not even the first listed in the CDP neighbor output, but I think this one will probably be an easy fix since the management address is prefixed with "Management address(es)". I'll factor this into this issue as well.

**Comment by net9000** [comment]
@routetehpacketz maybe a problem on my end and a missing route to that VPC peer link subnet.   I added it and will re-run the script to see if works.  Either way if you have a logic that tells it to use the management address in CDP then that would work as long as their is IP connectivity between them.

**Comment by net9000** [comment]
@routetehpacketz looks like its working great man. 

 One more request, can you do an ARP scan for a specific network via a switch?  Say I want to scan anything in the ARP table that falls within 10.12.12.0/24?  Then have the script check for any ARP entries within that CIDR and discover just those.  I ask because I ran it against a large network yesterday and because of a missing route it didn't populate some of the CDP data because it couldn't ssh to the neighboring switch.  So instead of having to run it again against everything it would be nice to be able to run it against specific ARP table CIDR entries instead of every entry in the ARP table.

**Comment by routetehpacketz** [comment]
hey @net9000 

is there an ether-channel between the N5K and the 3750x?

**Comment by net9000** [comment]
@routetehpacketz No just a single trunk port as you can see from the CDP.

**Comment by routetehpacketz** [comment]
@net9000 and just to confirm, you can SSH into 10.100.1.15 from the PC you're running the script on?

**Comment by net9000** [comment]
Yes I can.   When I wasn't able to prior (due to missing route to VPC peer subnet) the script would report the uplink from the core to the 5k as the port.  Now its reporting the uplink between the 5k and 3750 stack.  The difference here is I can ssh into all of them from the machine I am running the script from whereas before, I couldn't ssh into the 5k because of the missing route.  

```
:/local-dp$ ssh admin@10.100.1.15
Password:
3750-stack#
```

**Comment by hildebrau** [comment]
I also have a Nexus core switch, with Catalysts hanging off of it.  
I was having the port UNKNOWN issue, until I went into the script and edited the part that ran a "show ether-channel summ" command and converted it to "show port-channel summ".  Then it worked a lot better.  However, it doesn't seem to be identifying the switch connected to the port channel and connecting to it to further follow the MAC to the final switch and interface.  

Did anyone else get it working in this configuration?
